# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5fac08b1e6da837b71b811b9d052dce4fb3da07209e23a0e479f13d1cc31ddbb13268f89b76f9af2937ac72cb0797e18dcc54db7cdd6136851113126e0d9770

test:
  secret_key_base: cb05553d7b883d4d8431f6c62ed7b2cb1bcf1fb27a7e9b960f120f3581eba49d309bcf7e67980903c941a991f7653d74dfef888e6a5860a59e5111c465226196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
